name: Test macOS
on: repository_dispatch
jobs:
  test_project:
    name: Test framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Prepare Tools
        run: |
          git lfs install --skip-smudge
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install swiftlint xcbeautify
          cd Pact-macOS-Example && carthage update --platform macos --no-use-binaries
      - name: Run tests
        run: |
          set -o pipefail && xcodebuild clean test -project Pact-macOS-Example/Pact-macOS-Example.xcodeproj -scheme Pact-macOS-Example -destination "platform=macOS,arch=x86_64" | xcbeautify
