name: Test macOS
on:
  push:
    branches:
      - master
jobs:
  test_project:
    name: Test framework
    runs-on: macOS-latest
    steps:
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Prepare Tools
        run: |
          git lfs install --skip-smudge
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install swiftlint xcbeautify
          cd Pact-macOS-Example && carthage update --platform macos --no-use-binaries
      - name: Run tests
        run: |
          set -o pipefail && xcodebuild clean test -project Pact-macOS-Example/Pact-macOS-Example.xcodeproj -scheme Pact-macOS-Example -destination "platform=macOS,arch=x86_64" | xcbeautify
