name: Test iOS project

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  test_ios:
    name: Run tests on macOS 11.0
    runs-on: macOS-11.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Prepare the tools
        run: |
          brew install rust
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install xcbeautify

      - name: Test the iOS project
        run: |
          cd Pact-iOS-Example
          carthage update --platform iOS
          set -o pipefail && xcodebuild clean test -project Pact-iOS-Example.xcodeproj -scheme Pact-iOS-Example -destination "platform=iOS Simulator,name=iPhone 12 Pro" | xcbeautify
