name: Test iOS (Objective-C) project

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  test_ios:
    name: Run tests
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 11.7
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app

      - name: Prepare the tools
        run: |
          brew install rust
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install swiftlint xcbeautify

      - name: Cache Rust targets
        uses: actions/cache@v2
        with:
          path: Submodules/pact-reference/rust/target
          key: ${{ runner.os }}-pactswift-examples-submodule-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-pactswift-examples-submodule-
            ${{ runner.os }}-

      - name: Test the iOS (Objective-C) project
        run: |
          cd Pact-iOS-ObjC-Example
          ../carthage_xcode12 update --platform iOS
          set -o pipefail && xcodebuild clean test -project Pact-iOS-ObjC-Example.xcodeproj -scheme Pact-iOS-ObjC-Example -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcbeautify
